//! Regression tests for bugs fixed in v0.1.0–v0.1.11.
//! Each test ties back to a specific bug or inbox note.

use shytti::config::Config;
use shytti::shell::{ShellManager, SpawnRequest};
use shytti::control;

use std::path::PathBuf;

// --- Config parsing regressions ---

#[test]
fn config_shell_section_bootstrap_compat() {
    // Bug: Hermytt bootstrap writes [shell] default = "/bin/zsh"
    // but shytti expected [defaults] shell = "/bin/zsh". Silently ignored.
    // Fixed: build #16
    let content = r#"
[hermytt]
url = "http://10.10.0.3:7777"
token = "abc123"

[shell]
default = "/bin/zsh"
"#;
    let p = PathBuf::from(format!("/tmp/shytti_reg_shell_section_{}.toml", std::process::id()));
    std::fs::write(&p, content).unwrap();
    let cfg = Config::load(Some(p.clone())).unwrap();
    std::fs::remove_file(&p).ok();

    assert_eq!(cfg.defaults.shell, "/bin/zsh");
    assert_eq!(cfg.daemon.hermytt_url, "http://10.10.0.3:7777");
}

#[test]
fn config_shell_section_overrides_default() {
    // The [shell] section should override the compiled-in default
    let content = r#"
[shell]
default = "/bin/fish"
"#;
    let p = PathBuf::from(format!("/tmp/shytti_reg_shell_override_{}.toml", std::process::id()));
    std::fs::write(&p, content).unwrap();
    let cfg = Config::load(Some(p.clone())).unwrap();
    std::fs::remove_file(&p).ok();

    assert_eq!(cfg.defaults.shell, "/bin/fish");
}

#[test]
fn config_defaults_section_still_works() {
    // Original [defaults] format must still work
    let content = r#"
[defaults]
shell = "/bin/bash"
scrollback = 5000
"#;
    let p = PathBuf::from(format!("/tmp/shytti_reg_defaults_{}.toml", std::process::id()));
    std::fs::write(&p, content).unwrap();
    let cfg = Config::load(Some(p.clone())).unwrap();
    std::fs::remove_file(&p).ok();

    assert_eq!(cfg.defaults.shell, "/bin/bash");
    assert_eq!(cfg.defaults.scrollback, 5000);
}

// --- Session ID uniqueness ---

#[test]
fn session_ids_contain_timestamp() {
    // Bug: counter reset on restart could produce duplicate IDs if PID matched.
    // Fixed: build #8 — added epoch timestamp to IDs.
    let mgr = ShellManager::new();
    // IDs are generated by next_id() internally — we can't call it directly,
    // but we can verify spawned shells have unique, timestamp-bearing IDs.
    let rt = tokio::runtime::Runtime::new().unwrap();
    let id1 = rt.block_on(async {
        mgr.spawn(SpawnRequest {
            name: Some("ts-test-1".into()),
            shell: None, cwd: None, host: None, agent: None,
            cmd: Some("sleep 1".into()),
        }).await.unwrap()
    });
    let id2 = rt.block_on(async {
        mgr.spawn(SpawnRequest {
            name: Some("ts-test-2".into()),
            shell: None, cwd: None, host: None, agent: None,
            cmd: Some("sleep 1".into()),
        }).await.unwrap()
    });

    assert_ne!(id1, id2);
    // Format: {pid_hex}-{epoch_hex}-{counter}
    assert_eq!(id1.matches('-').count(), 2, "ID should have 3 segments: {id1}");
    assert_eq!(id2.matches('-').count(), 2, "ID should have 3 segments: {id2}");

    // Clean up
    rt.block_on(async { mgr.kill(&id1).await.ok(); mgr.kill(&id2).await.ok(); });
}

// --- Default shell wiring ---

#[tokio::test]
async fn manager_uses_config_default_shell() {
    // Bug: config default shell was parsed but never used in spawn.
    // ShellManager hardcoded /bin/zsh as fallback.
    // Fixed: build #17 — with_default_shell threads config through.
    let mgr = ShellManager::with_default_shell("/bin/sh".into());

    // Spawn with shell=None — should use the configured default, not hardcoded /bin/zsh
    let id = mgr.spawn(SpawnRequest {
        name: Some("default-shell-test".into()),
        shell: None,
        cwd: None, host: None, agent: None, cmd: None,
    }).await.unwrap();

    let shells = mgr.list().await;
    let shell = shells.iter().find(|s| s.id == id).unwrap();
    assert_eq!(shell.shell_type, shytti::shell::ShellType::Local);

    mgr.kill(&id).await.ok();
}

#[tokio::test]
async fn explicit_shell_overrides_default() {
    // When spawn request specifies a shell, it should override the config default.
    let mgr = ShellManager::with_default_shell("/bin/sh".into());

    let id = mgr.spawn(SpawnRequest {
        name: Some("explicit-shell-test".into()),
        shell: Some("/bin/zsh".into()),
        cwd: None, host: None, agent: None, cmd: None,
    }).await.unwrap();

    let shells = mgr.list().await;
    assert!(shells.iter().any(|s| s.id == id));

    mgr.kill(&id).await.ok();
}

// --- Session recovery ---

#[tokio::test]
async fn session_id_set_and_get() {
    // Supports list_shells: session_id must be stored and retrievable.
    let mgr = ShellManager::new();
    let id = mgr.spawn(SpawnRequest {
        name: Some("session-test".into()),
        shell: None, cwd: None, host: None, agent: None,
        cmd: Some("sleep 60".into()),
    }).await.unwrap();

    assert!(mgr.get_session_id(&id).await.is_none());

    mgr.set_session_id(&id, "sess-abc").await;
    assert_eq!(mgr.get_session_id(&id).await, Some("sess-abc".into()));

    // Reverse lookup
    assert_eq!(mgr.shell_id_by_session("sess-abc").await, Some(id.clone()));
    assert_eq!(mgr.shell_id_by_session("nonexistent").await, None);

    mgr.kill(&id).await.ok();
}

#[tokio::test]
async fn get_reader_writer_after_spawn() {
    // Bug: data relay failed after reconnect because reader/writer weren't available.
    // The reader/writer must be obtainable for any live shell.
    // Fixed: build #22 — re-attach on list_shells.
    let mgr = ShellManager::new();
    let id = mgr.spawn(SpawnRequest {
        name: Some("rw-test".into()),
        shell: None, cwd: None, host: None, agent: None,
        cmd: Some("sleep 60".into()),
    }).await.unwrap();

    let result = mgr.get_reader_writer(&id).await;
    assert!(result.is_ok(), "get_reader_writer should succeed for live shell");

    mgr.kill(&id).await.ok();
}

// --- Control protocol ---

#[test]
fn control_msg_list_shells_roundtrip() {
    // list_shells must serialize/deserialize correctly
    let msg = r#"{"type":"list_shells"}"#;
    let parsed: Result<control::ControlMsg, _> = serde_json::from_str(msg);
    assert!(parsed.is_ok(), "list_shells should parse: {:?}", parsed.err());
    assert!(matches!(parsed.unwrap(), control::ControlMsg::ListShells));
}

#[test]
fn control_msg_shells_list_roundtrip() {
    let msg = control::ControlMsg::ShellsList {
        shells: vec![
            control::ShellListEntry {
                shell_id: "abc".into(),
                session_id: "sess-1".into(),
            },
            control::ShellListEntry {
                shell_id: "def".into(),
                session_id: "sess-2".into(),
            },
        ],
    };
    let json = serde_json::to_string(&msg).unwrap();
    assert!(json.contains("\"type\":\"shells_list\""));
    assert!(json.contains("\"shell_id\":\"abc\""));

    let parsed: control::ControlMsg = serde_json::from_str(&json).unwrap();
    match parsed {
        control::ControlMsg::ShellsList { shells } => {
            assert_eq!(shells.len(), 2);
            assert_eq!(shells[0].shell_id, "abc");
            assert_eq!(shells[1].session_id, "sess-2");
        }
        _ => panic!("expected ShellsList"),
    }
}

#[test]
fn unknown_control_msg_does_not_parse() {
    // Bug: unknown message types should fail to parse gracefully,
    // not crash the control loop.
    // The parse_msg function returns None, control loop continues.
    let msg = r#"{"type":"future_message","data":"whatever"}"#;
    let parsed: Result<control::ControlMsg, _> = serde_json::from_str(msg);
    assert!(parsed.is_err(), "unknown type should fail serde parse");
}

#[test]
fn control_msg_without_type_does_not_parse() {
    let msg = r#"{"status":"ok"}"#;
    let parsed: Result<control::ControlMsg, _> = serde_json::from_str(msg);
    assert!(parsed.is_err(), "missing type field should fail");
}

// --- Pairing ---

#[test]
fn pair_token_roundtrip() {
    let (_token, encoded) = control::PairToken::generate("0.0.0.0:7778");
    let decoded = control::PairToken::decode(&encoded).unwrap();
    assert_eq!(decoded.port, 7778);
    assert!(!decoded.key.is_empty());
}

#[test]
fn long_lived_key_format() {
    let key = control::gen_long_lived_key();
    assert!(key.starts_with("sk-"), "key should start with sk-: {key}");
    assert!(key.len() > 10, "key should be reasonably long: {key}");
}

// --- Phantom shell pruning ---

#[tokio::test]
async fn prune_dead_keeps_live_shells() {
    // Bug: stale shells in shytti's map flooded Hermytt's registry on reconnect.
    // Fixed: build #27 — verify-on-list prunes dead shells before responding.
    //
    // We test the safe direction: prune_dead must NOT remove live shells.
    // Killing-side coverage is exercised by the death watcher in shell.rs.
    let mgr = ShellManager::new();

    let id1 = mgr.spawn(SpawnRequest {
        name: Some("alive-1".into()),
        shell: None, cwd: None, host: None, agent: None,
        cmd: Some("sleep 60".into()),
    }).await.unwrap();
    let id2 = mgr.spawn(SpawnRequest {
        name: Some("alive-2".into()),
        shell: None, cwd: None, host: None, agent: None,
        cmd: Some("sleep 60".into()),
    }).await.unwrap();

    tokio::time::sleep(std::time::Duration::from_millis(100)).await;

    let pruned = mgr.prune_dead().await;
    assert!(pruned.is_empty(), "live shells should not be pruned: {pruned:?}");

    let remaining: Vec<String> = mgr.list().await.iter().map(|s| s.id.clone()).collect();
    assert!(remaining.contains(&id1));
    assert!(remaining.contains(&id2));

    mgr.kill(&id1).await.ok();
    mgr.kill(&id2).await.ok();
}

#[tokio::test]
async fn prune_dead_on_empty_manager() {
    let mgr = ShellManager::new();
    let pruned = mgr.prune_dead().await;
    assert!(pruned.is_empty());
}
